### ISSUE TITLE
Master to Main

### ISSUE THREAD

**Issue by rainleander** [packethost/standards#60] opened 2020-09-03 07:26 UTC
Let's change the master branches to main on all PacketHost / Packet-Labs repositories.

**Comment by rainleander** [comment] 2020-09-03 07:53
Sent an email to the DevRel list to start this conversation internally. Also, @linuxjedi provided some useful links:

https://bbc.com/news/technology-53050955
https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html

**Comment by thebsdbox** [comment] 2020-09-03 12:22
This is excellent, a lot of our docs reference specific files in our repos so we'll need to ensure urls like `https://github.com/packethost/packngo/blob/master/devices_test.go` are caught as they're littered through our docs although should be easy and quick to find and replace.

**Comment by displague** [comment] 2020-09-03 12:28
https://github.com/github/renaming#from-master-to-main

https://docs.github.com/en/github/administering-a-repository/setting-the-default-branch
* https://github.com/organizations/packethost/settings/repository-defaults
* https://github.com/organizations/packet-labs/settings/repository-defaults
* https://github.com/organizations/tinkerbell/settings/repository-defaults

**Comment by displague** [comment] 2021-04-19 15:20
Renamed the default branch in this project to main.
Also - the default branch in the aforementioned orgs is set to 'main'.

To @thebsdbox's point, GitHub will redirect users from the old default branch name to the new one, so our old links will continue to work and we don't have to revise them all at once.

**Comment by displague** [comment] 2021-04-19 18:08
I'm going to close this issue out as the work has been applied in this project.
There are other projects in the organizations listed previously (also the Equinix organization) which have yet to adapt the `main` branch. Tracking those movements indirectly from this issue is difficult. We can create new issues on each repo that has the problem (the crux of the issue is simpler, knowing that GitHub redirects the URL even for git).

**Closed by displague** 2021-04-19 18:08 UTC
